<a href="https://colab.research.google.com/github/FendyDeveloper/Bank-Transaction-Dataset-for-Fraud-Detection/blob/main/%5BKlasifikasi%5D_Submission_Akhir_BMLP_Fendy%20Rahmat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

# **2. Memuat Dataset dari Hasil Clustering**

Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [ ]:
df = pd.read_csv('data_cluster.csv')
df

TransactionAmount TransactionType          Location Channel  \
0                 14.09           Debit         San Diego     ATM   
1                376.24           Debit           Houston     ATM   
2                126.29           Debit              Mesa  Online   
3                184.50           Debit           Raleigh  Online   
4                 13.45          Credit           Atlanta  Online   
...                 ...             ...               ...     ...   
2507             856.21          Credit  Colorado Springs  Branch   
2508             251.54           Debit            Tucson  Branch   
2509              28.63           Debit         San Diego  Branch   
2510             185.97           Debit            Denver  Online   
2511             243.08          Credit      Jacksonville  Online   

      CustomerAge CustomerOccupation  TransactionDuration  LoginAttempts  \
0            70.0             Doctor                 81.0            1.0   
1            68.0             Doctor                141.0            1.0   
2            19.0            Student                 56.0            1.0   
3            26.0            Student                 25.0            1.0   
4            26.0            Student                198.0            1.0   
...           ...                ...                  ...            ...   
2507         33.0             Doctor                109.0            1.0   
2508         48.0             Doctor                177.0            1.0   
2509         56.0            Retired                146.0            1.0   
2510         23.0            Student                 19.0            1.0   
2511         24.0            Student                 93.0            1.0   

      AccountBalance  DaysBetweenTransaction  Cluster  
0            5112.21                     572        2  
1           13758.91                     495        1  
2            1122.35                     482        1  
3            8569.06                     548        1  
4            7429.40                     384        0  
...              ...                     ...      ...  
2507        12690.79                     557        2  
2508          254.75                     592        2  
2509         3382.91                     440        1  
2510         1776.91                     618        2  
2511          131.25                     628        2  

[2512 rows x 11 columns]

In [ ]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label_object = ['TransactionType', 'Location', 'Channel', 'CustomerOccupation']
for i in label_object:
  df[i] = le.fit_transform(df[i])
df.head()

TransactionAmount  TransactionType  Location  Channel  CustomerAge  \
0              14.09                1        36        0         70.0   
1             376.24                1        15        0         68.0   
2             126.29                1        23        2         19.0   
3             184.50                1        33        2         26.0   
4              13.45                0         1        2         26.0   

   CustomerOccupation  TransactionDuration  LoginAttempts  AccountBalance  \
0                   0                 81.0            1.0         5112.21   
1                   0                141.0            1.0        13758.91   
2                   3                 56.0            1.0         1122.35   
3                   3                 25.0            1.0         8569.06   
4                   3                198.0            1.0         7429.40   

   DaysBetweenTransaction  Cluster  
0                     572        0  
1                     495        0  
2                     482        3  
3                     548        3  
4                     384        3

# **3. Data Splitting**

Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [ ]:
X = df.drop('Cluster', axis=1)
y = df['Cluster']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X

TransactionAmount  TransactionType  Location  Channel  CustomerAge  \
0                 14.09                1        36        0         70.0   
1                376.24                1        15        0         68.0   
2                126.29                1        23        2         19.0   
3                184.50                1        33        2         26.0   
4                 13.45                0         1        2         26.0   
...                 ...              ...       ...      ...          ...   
2507             856.21                0         7        1         33.0   
2508             251.54                1        40        1         48.0   
2509              28.63                1        36        1         56.0   
2510             185.97                1        10        2         23.0   
2511             243.08                0        17        2         24.0   

      CustomerOccupation  TransactionDuration  LoginAttempts  AccountBalance  \
0                      0                 81.0            1.0         5112.21   
1                      0                141.0            1.0        13758.91   
2                      3                 56.0            1.0         1122.35   
3                      3                 25.0            1.0         8569.06   
4                      3                198.0            1.0         7429.40   
...                  ...                  ...            ...             ...   
2507                   0                109.0            1.0        12690.79   
2508                   0                177.0            1.0          254.75   
2509                   2                146.0            1.0         3382.91   
2510                   3                 19.0            1.0         1776.91   
2511                   3                 93.0            1.0          131.25   

      DaysBetweenTransaction  
0                        572  
1                        495  
2                        482  
3                        548  
4                        384  
...                      ...  
2507                     557  
2508                     592  
2509                     440  
2510                     618  
2511                     628  

[2512 rows x 10 columns]

In [ ]:
y

0       0
1       0
2       3
3       3
4       3
       ..
2507    0
2508    0
2509    2
2510    3
2511    3
Name: Cluster, Length: 2512, dtype: int64

# **4. Membangun Model Klasifikasi**


## **a. Membangun Model Klasifikasi**

Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Pilih algoritma klasifikasi yang sesuai, seperti Logistic Regression, Decision Tree, Random Forest, atau K-Nearest Neighbors (KNN).
2. Latih model menggunakan data latih.

In [ ]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
lr = LogisticRegression(random_state=42)
lr.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=42)

Tulis narasi atau penjelasan algoritma yang Anda gunakan.

## **b. Evaluasi Model Klasifikasi**

Berikut adalah **rekomendasi** tahapannya.
1. Lakukan prediksi menggunakan data uji.
2. Hitung metrik evaluasi seperti Accuracy dan F1-Score (Opsional: Precision dan Recall).
3. Buat confusion matrix untuk melihat detail prediksi benar dan salah.

In [ ]:
y_pred_rf = rf.predict(X_test)
print("Random Forest - Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Random Forest - F1-Score:", f1_score(y_test, y_pred_rf, average='weighted'))

y_pred_lr = lr.predict(X_test)

Random Forest - Accuracy: 1.0
Random Forest - F1-Score: 1.0


In [ ]:
y_pred_lr = lr.predict(X_test)
print("Logistic Regression - Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Logistic Regression - F1-Score:", f1_score(y_test, y_pred_lr, average='weighted'))

Logistic Regression - Accuracy: 0.68389662027833
Logistic Regression - F1-Score: 0.6725142440461193


Tulis hasil evaluasi algoritma yang digunakan, jika Anda menggunakan 2 algoritma, maka bandingkan hasilnya.

## **c. Tuning Model Klasifikasi (Optional)**

Gunakan GridSearchCV, RandomizedSearchCV, atau metode lainnya untuk mencari kombinasi hyperparameter terbaik

In [ ]:
from sklearn.model_selection import GridSearchCV

# Contoh tuning untuk Random Forest
param_grid_rf = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Inisialisasi GridSearchCV
grid_search_rf = GridSearchCV(estimator=RandomForestClassifier(random_state=42),
                              param_grid=param_grid_rf,
                              scoring='f1_weighted',
                              cv=5,
                              n_jobs=-1)

# Melatih model dengan GridSearchCV
grid_search_rf.fit(X_train, y_train)

# Menampilkan hyperparameter terbaik
print("Best Parameters for Random Forest:", grid_search_rf.best_params_)

Best Parameters for Random Forest: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 50}


## **d. Evaluasi Model Klasifikasi setelah Tuning (Optional)**

Berikut adalah rekomendasi tahapannya.
1. Gunakan model dengan hyperparameter terbaik.
2. Hitung ulang metrik evaluasi untuk melihat apakah ada peningkatan performa.

In [ ]:
# Gunakan model dengan hyperparameter terbaik
best_rf_model = grid_search_rf.best_estimator_

# Prediksi menggunakan data uji
y_pred_best_rf = best_rf_model.predict(X_test)

# Hitung metrik evaluasi
accuracy_best_rf = accuracy_score(y_test, y_pred_best_rf)
f1_best_rf = f1_score(y_test, y_pred_best_rf, average='weighted')

# Bandingkan hasil sebelum dan sesudah tuning
print("Random Forest (Before Tuning) - Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Random Forest (Before Tuning) - F1-Score:", f1_score(y_test, y_pred_rf, average='weighted'))

print("Random Forest (After Tuning) - Accuracy:", accuracy_best_rf)
print("Random Forest (After Tuning) - F1-Score:", f1_best_rf)

Random Forest (Before Tuning) - Accuracy: 1.0
Random Forest (Before Tuning) - F1-Score: 1.0
Random Forest (After Tuning) - Accuracy: 1.0
Random Forest (After Tuning) - F1-Score: 1.0


In [ ]:
from sklearn.metrics import confusion_matrix
cm_lr = confusion_matrix(y_test, y_pred_rf)
print("Confusion Matrix for Logistic Regression:\n", cm_lr)

Confusion Matrix for Logistic Regression:
 [[124   0   0   0]
 [  0 112   0   0]
 [  0   0 138   0]
 [  0   0   0 129]]


In [ ]:
print("Class Distribution in Test Set:\n", y_test.value_counts())


Class Distribution in Test Set:
 Cluster
2    138
3    129
0    124
1    112
Name: count, dtype: int64


In [ ]:
from sklearn.model_selection import cross_val_score
cv_scores_rf = cross_val_score(rf, X, y, cv=5, scoring='f1_weighted')
print("Cross-Validation F1-Scores:", cv_scores_rf)
print("Mean CV F1-Score:", np.mean(cv_scores_rf))

Cross-Validation F1-Scores: [1. 1. 1. 1. 1.]
Mean CV F1-Score: 1.0


In [ ]:
feature_importances = rf.feature_importances_
for feature, importance in zip(X.columns, feature_importances):
    print(f"{feature}: {importance}")

TransactionAmount: 0.006627618057343304
TransactionType: 0.0005124019890164765
Location: 0.0058059186238903215
Channel: 0.0013381435081825214
CustomerAge: 0.21947282292324974
CustomerOccupation: 0.6229546814934546
TransactionDuration: 0.006206888732087561
LoginAttempts: 0.0005137267923395841
AccountBalance: 0.1306738735090333
DaysBetweenTransaction: 0.0058939243714027315


In [ ]:
from sklearn.metrics import confusion_matrix
cm_rf = confusion_matrix(y_test, y_pred_rf)
print("Confusion Matrix for Random Forest:\n", cm_rf)

Confusion Matrix for Random Forest:
 [[124   0   0   0]
 [  0 112   0   0]
 [  0   0 138   0]
 [  0   0   0 129]]


## **e. Analisis Hasil Evaluasi Model Klasifikasi**

Analisis Hasil Evaluasi Model Klasifikasi:

1. Performa Confusion Matrix:
   - Confusion Matrix menunjukkan bahwa model Random Forest berhasil memprediksi semua kelas dengan sempurna.
   - Tidak ada kesalahan klasifikasi, baik false positives maupun false negatives.

2. Identifikasi Kelemahan Model:
   - Overfitting: Performa sempurna pada confusion matrix menunjukkan bahwa model tidak mengalami overfitting.
   - Keseimbangan Kelas: Distribusi kelas dalam dataset seimbang, sehingga model tidak bias terhadap kelas tertentu.
   - Data Leakage: Tidak ada indikasi data leakage, tetapi perlu dipastikan bahwa fitur yang digunakan relevan dan tidak termasuk informasi sensitif.

3. Rekomendasi Tindakan Lanjutan:
   - Uji model pada dataset baru untuk memastikan generalisasi.
   - Eksplorasi algoritma lain seperti Gradient Boosting untuk membandingkan performa.
   - Lakukan feature importance analysis untuk memahami kontribusi setiap fitur terhadap prediksi.
   - Terapkan simulasi dunia nyata untuk memastikan bahwa model bekerja dengan baik di luar lingkungan eksperimen.